
# Configurações de Build
[build]
  # Comando para construir o site
  command = "npm run build"
  # Diretório que será publicado (deve ser 'out' para um Next.js estático)
  publish = "out"

# Regra de redirecionamento para Single Page Applications (SPAs)
[[redirects]]
  # Redireciona qualquer caminho que não seja um arquivo encontrado...
  from = "/*"
  # ...para o index.html principal.
  to = "/index.html"
  # Com o status 200, que significa "OK".
  status = 200
